package Team3;

public class Instruction {

    public static void getInstruction(){
        System.out.println(" There are our program and short description :  ");
        System.out.println(" 1.  ");
        System.out.println(" 2. This program return multiply of 2 numbers. Push 2 for start this program ");
        System.out.println(" 3. This program calculates the volume of the cuboid ");
        System.out.println(" 4.  ");
        System.out.println(" 5.  ");
        System.out.println(" 6. Convert Int to binary. Enter int number to console ");
        System.out.println(" 7. This program returns the time since midnight in milliseconds ");
        System.out.println(" 8.   ");
        System.out.println(" 9. ");
        System.out.println(" 10. It's the 'recommended' age range in which to date someone");
        System.out.println(" 11. This program converts fahrenheit to celsius  ");
        System.out.println(" 12.  ");
        System.out.println(" 13.   ");
        System.out.println(" 14.  ");
        System.out.println(" 15. ");
        System.out.println(" 16.   ");
        System.out.println(" 17. ");
        System.out.println(" 18. This program makes opposite of entered number ");
        System.out.println(" 19. This program checks if a number n is divisible by two numbers x AND y. All inputs must be a positive, non-zero digits.");
        System.out.println(" 20.  ");
        System.out.println(" 21.  ");
        System.out.println(" 22. This program calculates 'How old you will be' or 'how many years left before your birth");
        System.out.println(" 23. This program this program implements the game 'Rock Paper Scissors'");
        System.out.println(" 24.  ");
        System.out.println(" 25.  ");
        System.out.println(" 26. This program return String 'Yes' if boolean true and return 'No' if false");
        System.out.println(" 27. This program telling the driver if he will be able to fit all the passengers. ");
        System.out.println(" 28.  ");
        System.out.println(" 29.  ");
        System.out.println(" 30. This program switches color on traffic light");
        System.out.println(" 31. This program gives out the total amount for different days for rent a car");
        System.out.println(" 32.  ");
        System.out.println(" 33.  ");
        System.out.println(" 34. This program calculates average number from array");
        System.out.println(" 35. This program returns your array with each value doubled. ");
        System.out.println(" 36.  ");
        System.out.println(" 37.  ");
        System.out.println(" 38. This program checks if your marks better then average");
        System.out.println(" 39. This program  returns the result of multiplying the values together in order ");
        System.out.println(" 40.  ");
        System.out.println(" 41.  ");
        System.out.println(" 42. This program Сalculate how many years ago the father was twice as old as his son");
        System.out.println(" 43. This program  finds the nearest square number of a positive integer n ");
        System.out.println(" 44.  ");
        System.out.println(" 45.  ");
        System.out.println(" 46.  ");
        System.out.println(" 47.  ");
        System.out.println(" 48.  ");
        System.out.println(" 49.  ");
        System.out.println(" 50.  ");
        System.out.println(" 51. This program  transforms a number into a string ");
        System.out.println(" 52.  ");
        System.out.println(" 53.  ");
        System.out.println(" 54. This program makes opposite number");
        System.out.println(" 55. This program  replaces all the dots '.' in the specified String str with dashes '-' ");
        System.out.println(" 56.  ");
        System.out.println(" 57.  ");
        System.out.println(" 58. This program return a string that combines all of the letters of the three inputed strings in groups");
        System.out.println(" 59. This program return letters position in the alphabet. ");
        System.out.println(" 60.  ");
        System.out.println(" 61.  ");
        System.out.println(" 62. This program convert fahrenheit to celsius ");
        System.out.println(" 63. This program converts a name into initials ");
        System.out.println(" 64.  ");
        System.out.println(" 65.  ");
        System.out.println(" 66. This program replaces erroneous characters in the text");
        System.out.println(" 67. In this program lowercase letter becomes uppercase and each uppercase letter becomes lowercase ");
        System.out.println(" 68.  ");
        System.out.println(" 69.  ");
        System.out.println(" 70. This program create list of number ");
        System.out.println(" 71. This program removes even numbers from the list and return a list that contains odd number. ");
        System.out.println(" 72.  ");
    }
}
